update 202600419

diff --git a/neos_main b/neos_main
--- a/neos_main
+++ b/neos_main
@@ -6,22 +6,6 @@ source /usr/local/bin/bash_colors.sh
 # bash scripts I made so far
 
 
-echo -e "Choose:
-tree  - Reports Tree,                 Args   'R-127' etc
-2     - fzf Asset,                    Nan
-rep   - Un-submitted reports,         Nan
-4     - Copy array of files,          Fill   ~/Downloads/list_of_asset_array.txt
-dp    - GOES Depth,                   Args   select files
-dpl   - GOES Depth loop,              Nan    will loop
-7     - Check database,               Fill   ~/Downloads/check_asset_exist.txt
-sqb   - Find SQB,                     Args   R-338 etc
-sync  - rsync server,                 Nan
-10    - Sweeb expired files           Args   [-m|-d] 20251210 ./
-99    - Make all html                 Nan
-rqc   - Find No-RQC reports           Nan"
-read -p "Select: " num
-echo "================================="
-
 function find-sqb() {
     local sqb_dir="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/SQB/"
     # Check if the directory available or not!
@@ -52,6 +36,21 @@ function depth_loop() {
     find . -type f -name "*.csv" -exec neos_goes_depth {} \;
 }
 
+function sgs_max_val_loop() {
+    find . -type f -name "*.txt" -exec neos_sgs_max_values {} \;
+}
+
+function export_database() {
+   sqlite3 -header -csv "$HOME/org/neosdatabase.db" "SELECT * FROM sl_equipment;" > ~/org/Exported_database_2026_noes.csv
+   sqlite3 -header -csv "$HOME/org/neosdatabase.db" "SELECT * FROM personnel_sl;" > ~/org/Exported_database_2026_noes_personnel.csv
+
+   if [[ $? -eq 0 ]]; then
+       echo -e "${CYAN}Database exported to CSV${NC}"
+   else
+       echo -e "${RED}Database export FAILED${NC}" >&2
+   fi 
+}
+
 function find-no-rqc() {
     local path1="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit1/Daily Report/2026/"
     local path2="/Volumes/WL-SL/02 Slickline/01 Jobs/BECL BP/Unit2/Daily Report/2026/"
@@ -66,18 +65,47 @@ function make-all() {
     make all
 }
 
+function asset-register-update() {
+    export_database
+    cd "~/Desktop/html_generator/html_asset_register/"
+    make run-all
+}
+
+# while true; do
+echo -e "\nChoose:
+    tree  - Reports Tree,                 Args   'R-127' etc
+    rep   - Un-submitted reports,         Nan
+    sgs   - SGS max loop,                 Nan    will loop
+    dp    - GOES Depth loop,              Nan    will loop
+    sqb   - Find SQB,                     Args   R-338 etc
+    sync  - rsync server,                 Nan
+    rqc   - Find No-RQC reports           Nan
+    1     - fzf Asset,                    Nan
+    4     - Copy array of files,          Fill   ~/Downloads/list_of_asset_array.txt
+    7     - Check database,               Fill   ~/Downloads/check_asset_exist.txt
+    10    - Sweeb expired files           Args   [-m|-d] 20251210 ./
+    99    - Make all html                 Nan
+    expo  - Export database               Nan
+    q     - Quit"
+read -p "Select: " num
+echo "================================="
+
 case $num in
-  tree) neos_tree_reports "$@";;
-  2) neosfzf "$@";;
-  rep) check_missing_reports;;
-  4) neos_array_copy;;
-  dp) neos_goes_depth "$@";;
-  dpl) depth_loop;;
-  7) neos_check_asset_in_database;;
-  sqb) find-sqb "$@";;
-  sync) server_rsync;;
-  10) sweeb_expired_files "$@";;
-  99) make-all;;
-  rqc) find-no-rqc;;
-  *) echo "Wrong selection";;
+    tree) neos_tree_reports "$@";;
+    1) neosfzf "$@";;
+    rep) check_missing_reports;;
+    expo) export_database;;
+    4) neos_array_copy;;
+    sgs) sgs_max_val_loop;;
+    dp) depth_loop;;
+    7) neos_check_asset_in_database;;
+    sqb) find-sqb "$@";;
+    sync) server_rsync;;
+    # regis) asset-register-update;;
+    10) sweeb_expired_files "$@";;
+    99) make-all;; 
+    rqc) find-no-rqc;;
+    q|Q) echo "Goodby"; break;;
+    *) echo -e "${RED}Wrong selection${NC}";;
 esac
+# done
